/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package base.panel;

import base.classification.Category;

/**
 *
 * @author Mahdi
 */
public class CategoryViewer extends javax.swing.JPanel {

    /**
     * Creates new form CategoryViewer
     */
    public CategoryViewer() {
        initComponents();
    }

    public void view(Category category) {
        if(category == null){
            System.out.println("category is null");
            return;
        }
        String startHtml = "<html><div dir=\"rtl\" style=\"padding: 10px\">";
        String endHtml = "</div></html>";
        if (category.getIcon() != null) {
            catIcon.setIcon(new javax.swing.ImageIcon(category.getIcon().getUrl()));
        }else{
            System.out.println("category icon is null");
        }
        catName.setText(startHtml + category.getName().getFarsi() + endHtml);
        catDescription.setText(startHtml + category.getDescription().getFarsi() + endHtml);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catIcon = new javax.swing.JLabel();
        catName = new javax.swing.JLabel();
        catDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        catIcon.setBackground(new java.awt.Color(255, 255, 255));
        catIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catIcon.setIcon(new javax.swing.ImageIcon("D:\\Dadehkhan_pics\\Irankhodro.gif")); // NOI18N
        catIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 1, true));
        catIcon.setOpaque(true);

        catName.setBackground(new java.awt.Color(255, 255, 255));
        catName.setFont(new java.awt.Font("B Koodak", 0, 36)); // NOI18N
        catName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        catName.setText(" ایران خودرو");
        catName.setOpaque(true);

        catDescription.setBackground(new java.awt.Color(255, 255, 255));
        catDescription.setFont(new java.awt.Font("B Mitra", 0, 18)); // NOI18N
        catDescription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        catDescription.setComponentOrientation(java.awt.ComponentOrientation.RIGHT_TO_LEFT);
        catDescription.setText("<html><div dir=\"rtl\" style=\"padding: 10px\">\nگروه خودرو سازی ایران خودرو تولید کننده خودرو های پژو ، سمند ، تندر 90 و ویتارا میباشد.\n</div></html>");
        catDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        catDescription.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        catDescription.setOpaque(true);

        jTable1.setComponentOrientation(java.awt.ComponentOrientation.RIGHT_TO_LEFT);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"پژو 206 تیپ 2",  new Long(32),  new Long(30)},
                {"پژو 206 تیپ 5",  new Long(38),  new Long(36)},
                {"سمند",  new Long(19),  new Long(18)},
                {"ویتارا",  new Long(80),  new Long(75)}
            },
            new String [] {
                "نام کالا", "قیمت بازار", "قیمت نمایندگی"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(catIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(catName, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
            .addComponent(catDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(catDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catDescription;
    private javax.swing.JLabel catIcon;
    private javax.swing.JLabel catName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
