/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package base.panel;

import base.Config;
import base.applicator.object.StandardEntity;
import base.applicator.object.Stuff;
import base.classification.Category;
import base.classification.EntityType;
import base.util.EntityID;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author Mahdi
 */
public class CategoryViewer extends javax.swing.JPanel {

    /**
     * Creates new form CategoryViewer
     */
    public CategoryViewer() {
        initComponents();
    }

    public void view(Category category) {
        if (category == null) {
            System.out.println("category is null");
            return;
        }
        String startHtml = "<html><div dir=\"rtl\" style=\"padding: 10px\">";
        String endHtml = "</div></html>";
        if (category.getIcon() != null) {
            catIcon.setIcon(new javax.swing.ImageIcon(category.getIcon().getUrl()));
        } else {
            System.out.println("category icon is null");
        }
        catName.setText(startHtml + category.getName().get(Config.DEFAULT_LANGUAGE) + endHtml);
        catDescription.setText(startHtml + category.getDescription().get(Config.DEFAULT_LANGUAGE) + endHtml);
        jTable1.setModel(convertToModel(category));
    }

    private TableModel convertToModel(Category category) {
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        List<String> columns = new ArrayList<>();
        String name, varName;
        Map<String, Integer> nameIndexMap = new HashMap<>();
        columns.add("ID");
        columns.add("نام کالا");
        columns.add("شاخه");
        columns.add("تعداد فیلد");
        for (String col : columns) {
            model.addColumn(col);
        }
        Object[] row;
        Stuff stuff;
        int i;
        for (StandardEntity entity : category.getItems()) {
            stuff = (Stuff) entity;
            row = new Object[4];
            i=0;
            row[i++] = entity.getId();
            row[i++] = entity.getName().get(Config.DEFAULT_LANGUAGE);
            row[i++] = stuff.getCategory() == null ? "-" : stuff.getCategory().getName().get(Config.DEFAULT_LANGUAGE);
            row[i++] = stuff.getReferences().size();
            model.addRow(row);
        }
        return model;
    }
    
    private ContentPanel contentPanel;

    public void setContentPanel(ContentPanel contentPanel) {
        this.contentPanel = contentPanel;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catIcon = new javax.swing.JLabel();
        catName = new javax.swing.JLabel();
        catDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        catIcon.setBackground(new java.awt.Color(255, 255, 255));
        catIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 1, true));
        catIcon.setOpaque(true);

        catName.setBackground(new java.awt.Color(255, 255, 255));
        catName.setFont(new java.awt.Font("B Koodak", 0, 36)); // NOI18N
        catName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        catName.setText(" ایران خودرو");
        catName.setOpaque(true);

        catDescription.setBackground(new java.awt.Color(255, 255, 255));
        catDescription.setFont(new java.awt.Font("B Mitra", 0, 18)); // NOI18N
        catDescription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        catDescription.setComponentOrientation(java.awt.ComponentOrientation.RIGHT_TO_LEFT);
        catDescription.setText("<html><div dir=\"rtl\" style=\"padding: 10px\">\nگروه خودرو سازی ایران خودرو تولید کننده خودرو های پژو ، سمند ، تندر 90 و ویتارا میباشد.\n</div></html>");
        catDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        catDescription.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        catDescription.setOpaque(true);

        jTable1.setComponentOrientation(java.awt.ComponentOrientation.RIGHT_TO_LEFT);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"پژو 206 تیپ 2",  new Long(32),  new Long(30)},
                {"پژو 206 تیپ 5",  new Long(38),  new Long(36)},
                {"سمند",  new Long(19),  new Long(18)},
                {"ویتارا",  new Long(80),  new Long(75)}
            },
            new String [] {
                "نام کالا", "قیمت بازار", "قیمت نمایندگی"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectItemEvent(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(catIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(catName, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
            .addComponent(catDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(catDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectItemEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectItemEvent
        if(evt.getClickCount()>=2){
            int row = jTable1.rowAtPoint(evt.getPoint());
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            EntityID id = (EntityID)model.getValueAt(row, 0);
            contentPanel.showItem(id, EntityType.CAR);
        }
    }//GEN-LAST:event_selectItemEvent

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catDescription;
    private javax.swing.JLabel catIcon;
    private javax.swing.JLabel catName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
