/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package base.panel;

import base.classification.Category;
import base.grabber.GrabManager;
import base.util.EntityID;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Box;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Mahdi
 */
public class CategoryPanel extends javax.swing.JPanel {

    Map<Integer, Category> labelCategoryMap = new HashMap<Integer, Category>();
    Category presentCategory = null;
    private GrabManager grabManager;

    /**
     * Creates new form CategoryPanel
     */
    public CategoryPanel(GrabManager grabManager) {
        this.grabManager = grabManager;
        initComponents();
    }

    public CategoryPanel() {
        this.grabManager = null;
        initComponents();
    }

    public void show(Category category) {
        jList1.removeAll();
        presentCategory = category;
        int i = 0;
        DefaultListModel<String> model = new DefaultListModel<String>();
        for (Category cat : category.getSubCategories()) {
            model.add(i, cat.getName().getFarsi());
            labelCategoryMap.put(i, cat);
            i++;
        }
        jList1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryViewer1 = new base.panel.CategoryViewer();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        categoryViewer1.setOpaque(true);

        jList1.setComponentOrientation(java.awt.ComponentOrientation.RIGHT_TO_LEFT);
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "ایران خودرو", "سایپا", "پارس خودرو", "کرمان خودرو", "آسا موتورز" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(categoryViewer1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoryViewer1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        Category cat = labelCategoryMap.get(jList1.getSelectedIndex());
        categoryViewer1.view(cat);
    }//GEN-LAST:event_jList1ValueChanged

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
//        if (evt.getClickCount() >= 2) {
//        }
    }//GEN-LAST:event_jList1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private base.panel.CategoryViewer categoryViewer1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
