/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package base.panel;

import base.Config;
import base.classification.Category;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Mahdi
 */
public class NavigationPanel extends javax.swing.JPanel {

    private ContentPanel contentPanel;
    private Map<String , Category> labelCategoryMap = new HashMap<>();

    /**
     * Creates new form NavigationPanel
     */
    public NavigationPanel() {
        initComponents();
    }

    public void show(Category category) {
        List<Category> parents = new ArrayList<>();
        Category parent = category/* == null ? null : category.getParent()*/;
        jToolBar1.removeAll();
        jToolBar1.add(javax.swing.Box.createHorizontalGlue());
        while (parent != null) {
            parent = parent.getParent();
            if (parent != null) {
                parents.add(parent);
            }
        }
        String txt = category == null ? "NULL" : category.getName().get(Config.DEFAULT_LANGUAGE);
        labelCategoryMap.put(txt, category);
        addLabel(txt , true);
        for (Category cat : parents) {
            addLabel(" « ", false);
            labelCategoryMap.put(cat.getName().get(Config.DEFAULT_LANGUAGE),cat);
            addLabel(cat.getName().get(Config.DEFAULT_LANGUAGE),true);
        }
    }

    private void addLabel(String text, boolean link) {
        final Font font = new java.awt.Font("B Mitra", 0, 18);
        final javax.swing.JLabel label = new javax.swing.JLabel();
        label.setFont(font);
        label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label.setText(text);
        if(link){
            label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            label.addMouseListener(new MouseAdapter() {

                @Override
                public void mouseClicked(MouseEvent e) {
                    Category cat = labelCategoryMap.get(label.getText());
                    contentPanel.setCategory(cat);
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    label.setForeground(Color.BLUE);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    label.setForeground(Color.BLACK);
                }
            });
        }
        jToolBar1.add(label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(javax.swing.Box.createHorizontalGlue());

        jLabel6.setFont(new java.awt.Font("B Mitra", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("کالا");
        jToolBar1.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("B Mitra", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(" » ");
        jToolBar1.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("B Mitra", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("خودرو");
        jToolBar1.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("B Mitra", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText(" » ");
        jToolBar1.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("B Mitra", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("داخلی");
        jToolBar1.add(jLabel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    void setContentPanel(ContentPanel contentPanel) {
        this.contentPanel = contentPanel;
    }
}
